from models import Movimiento

equipo_con_6_pokemons = {
    "id_equipo": 1,
    "nombre": "Equipo Elite",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo_siete_pokemons = {
    "id_equipo": 2,
    "nombre": "Equipo Sobrecargado",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                }
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 4,
            "nombre": "Gyarados",
            "naturaleza": {
                "id": 7,
                "nombre": "Bashful",
                "aumenta_estadistica": "Defensa",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 8,
                    "nombre": "Tierra",
                    "tipo": "Tierra",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "IV",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo_mismo_id = {
    "id_equipo": 1,
    "nombre": "Equipo Filete",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo = {
    "id_equipo": 2,
    "nombre": "Equipo Elite",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
infernape_mock = {
        "pokemon_id": 392,
        "nombre": "infernape",
        "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/392.png",
        "tipos": ["Lucha", "Fuego"],
        "habilidades": ["Mar Llamas", "Puño Férreo"],
        'movimientos_ids': [10,
                     14,
                     15,
                     43,
                     46,
                     52,
                     53,
                     63,
                     70,
                     76,
                     83,
                     89,
                     91,
                     92,
                     104,
                     126,
                     154,
                     156,
                     157,
                     164,
                     172,
                     182,
                     183,
                     203,
                     207,
                     213,
                     214,
                     216,
                     218,
                     231,
                     237,
                     241,
                     249,
                     259,
                     261,
                     263,
                     264,
                     269,
                     280,
                     290,
                     307,
                     315,
                     317,
                     332,
                     339,
                     347,
                     363,
                     364,
                     369,
                     370,
                     374,
                     386,
                     394,
                     398,
                     411,
                     416,
                     421,
                     431,
                     444,
                     445,
                     446,
                     447,
                     7,
                     9,
                     129,
                     173,
                     189,
                     205,
                     257,
                     270,
                     283,
                     410,
                     441,
                     29,
                     67,
                     272,
                     468,
                     488,
                     490,
                     496,
                     510,
                     512,
                     514,
                     519,
                     523,
                     526,
                     343,
                     530,
                     590,
                     612,
                     673],
        "altura": 12,
        "peso": 550,
        "estadisticas": {
            "hp": 76,
            "attack": 104,
            "defense": 71,
            "special-attack": 104,
            "special-defense": 71,
            "speed": 108,
            "accuracy": 0,
            "evasion": 0,
        },
        "cadena_evolutiva_ids": [390, 391, 392],
    }

movimientos_infernape = [
    Movimiento(id=10, nombre='scratch', tipo='Normal', power=40, accuracy=100, pp=35, generacion='Generation 1', categoria='físico', efecto='Inflicts regular damage with no additional effect.', probabilidad_efecto=None),
    Movimiento(id=14, nombre='swords-dance', tipo='Normal', power=None, accuracy=None, pp=20, generacion='Generation 1', categoria='estado', efecto="Raises the user's Attack by two stages.", probabilidad_efecto=None),
    Movimiento(id=15, nombre='cut', tipo='Normal', power=50, accuracy=95, pp=30, generacion='Generation 1', categoria='físico', efecto='Inflicts regular damage with no additional effect.', probabilidad_efecto=None),
    Movimiento(id=43, nombre='leer', tipo='Normal', power=None, accuracy=100, pp=30, generacion='Generation 1', categoria='estado', efecto="Lowers the target's Defense by one stage.", probabilidad_efecto=100),
    Movimiento(id=46, nombre='roar', tipo='Normal', power=None, accuracy=None, pp=20, generacion='Generation 1', categoria='estado', efecto='Immediately ends wild battles. Forces trainers to switch Pokémon.', probabilidad_efecto=None),
    Movimiento(id=52, nombre='ember', tipo='Fuego', power=40, accuracy=100, pp=25, generacion='Generation 1', categoria='especial', efecto='Has a $effect_chance% chance to [burn]{mechanic:burn} the target.', probabilidad_efecto=10),
    Movimiento(id=53, nombre='flamethrower', tipo='Fuego', power=90, accuracy=100, pp=15, generacion='Generation 1', categoria='especial', efecto='Has a $effect_chance% chance to [burn]{mechanic:burn} the target.', probabilidad_efecto=10),
    Movimiento(id=63, nombre='hyper-beam', tipo='Normal', power=150, accuracy=90, pp=5, generacion='Generation 1', categoria='especial', efecto='User foregoes its next turn to recharge.', probabilidad_efecto=None),
    Movimiento(id=70, nombre='strength', tipo='Normal', power=80, accuracy=100, pp=15, generacion='Generation 1', categoria='físico', efecto='Inflicts regular damage with no additional effect.', probabilidad_efecto=None),
    Movimiento(id=76, nombre='solar-beam', tipo='Planta', power=120, accuracy=100, pp=10, generacion='Generation 1', categoria='especial', efecto='Requires a turn to charge before attacking.', probabilidad_efecto=None),
    Movimiento(id=83, nombre='fire-spin', tipo='Fuego', power=35, accuracy=85, pp=15, generacion='Generation 1', categoria='especial', efecto='Prevents the target from fleeing and inflicts damage for 2-5 turns.', probabilidad_efecto=100),
    Movimiento(id=89, nombre='earthquake', tipo='Tierra', power=100, accuracy=100, pp=10, generacion='Generation 1', categoria='físico', efecto='Inflicts regular damage and can hit Dig users.', probabilidad_efecto=None),
    Movimiento(id=91, nombre='dig', tipo='Tierra', power=80, accuracy=100, pp=10, generacion='Generation 1', categoria='físico', efecto='User digs underground, dodging all attacks, and hits next turn.', probabilidad_efecto=None),
    Movimiento(id=92, nombre='toxic', tipo='Veneno', power=None, accuracy=90, pp=10, generacion='Generation 1', categoria='estado', efecto='Badly poisons the target, inflicting more damage every turn.', probabilidad_efecto=None),
    Movimiento(id=104, nombre='double-team', tipo='Normal', power=None, accuracy=None, pp=15, generacion='Generation 1', categoria='estado', efecto="Raises the user's evasion by one stage.", probabilidad_efecto=None),
    Movimiento(id=126, nombre='fire-blast', tipo='Fuego', power=110, accuracy=85, pp=5, generacion='Generation 1', categoria='especial', efecto='Has a $effect_chance% chance to [burn]{mechanic:burn} the target.', probabilidad_efecto=10),
    Movimiento(id=154, nombre='fury-swipes', tipo='Normal', power=18, accuracy=80, pp=15, generacion='Generation 1', categoria='físico', efecto='Hits 2-5 times in one turn.', probabilidad_efecto=None),
    Movimiento(id=156, nombre='rest', tipo='Psíquico', power=None, accuracy=None, pp=10, generacion='Generation 1', categoria='estado', efecto='User sleeps for two turns, completely healing itself.', probabilidad_efecto=None),
    Movimiento(id=157, nombre='rock-slide', tipo='Roca', power=75, accuracy=90, pp=10, generacion='Generation 1', categoria='físico', efecto='Has a $effect_chance% chance to make the target flinch.', probabilidad_efecto=30),
    Movimiento(id=164, nombre='substitute', tipo='Normal', power=None, accuracy=None, pp=10, generacion='Generation 1', categoria='estado', efecto="Transfers 1/4 of the user's max HP into a doll, protecting the user from further damage or status changes until it breaks.", probabilidad_efecto=None),
    Movimiento(id=172, nombre='flame-wheel', tipo='Fuego', power=60, accuracy=100, pp=25, generacion='Generation 2', categoria='físico', efecto='Has a $effect_chance% chance to [burn]{mechanic:burn} the target. Lets frozen Pokémon thaw themselves.', probabilidad_efecto=10),
    Movimiento(id=182, nombre='protect', tipo='Normal', power=None, accuracy=None, pp=10, generacion='Generation 2', categoria='estado', efecto='Prevents any moves from hitting the user this turn.', probabilidad_efecto=None),
    Movimiento(id=183, nombre='mach-punch', tipo='Lucha', power=40, accuracy=100, pp=30, generacion='Generation 2', categoria='físico', efecto='Inflicts regular damage with no additional effect.', probabilidad_efecto=None),
    Movimiento(id=203, nombre='endure', tipo='Normal', power=None, accuracy=None, pp=10, generacion='Generation 2', categoria='estado', efecto="Prevents the user's HP from lowering below 1 this turn.", probabilidad_efecto=None),
    Movimiento(id=207, nombre='swagger', tipo='Normal', power=None, accuracy=85, pp=15, generacion='Generation 2', categoria='estado', efecto="Raises the target's Attack by two stages and confuses the target.", probabilidad_efecto=None),
    Movimiento(id=213, nombre='attract', tipo='Normal', power=None, accuracy=100, pp=15, generacion='Generation 2', categoria='estado', efecto='Target falls in love if it has the opposite gender, and has a 50% chance to refuse attacking the user.', probabilidad_efecto=None),
    Movimiento(id=214, nombre='sleep-talk', tipo='Normal', power=None, accuracy=None, pp=10, generacion='Generation 2', categoria='estado', efecto="Randomly uses one of the user's other three moves. Only works if the user is sleeping.", probabilidad_efecto=None),
    Movimiento(id=216, nombre='return', tipo='Normal', power=None, accuracy=100, pp=20, generacion='Generation 2', categoria='físico', efecto='Power increases with happiness, up to a maximum of 102.', probabilidad_efecto=None),
    Movimiento(id=218, nombre='frustration', tipo='Normal', power=None, accuracy=100, pp=20, generacion='Generation 2', categoria='físico', efecto='Power increases as happiness decreases, up to a maximum of 102.', probabilidad_efecto=None),
    Movimiento(id=231, nombre='iron-tail', tipo='Acero', power=100, accuracy=75, pp=15, generacion='Generation 2', categoria='físico', efecto="Has a $effect_chance% chance to lower the target's Defense by one stage.", probabilidad_efecto=30),
    Movimiento(id=237, nombre='hidden-power', tipo='Normal', power=60, accuracy=100, pp=15, generacion='Generation 2', categoria='especial', efecto="Power and type depend upon user's IVs. Power can range from 30 to 70.", probabilidad_efecto=None),
    Movimiento(id=241, nombre='sunny-day', tipo='Fuego', power=None, accuracy=None, pp=5, generacion='Generation 2', categoria='estado', efecto='Changes the weather to sunny for five turns.', probabilidad_efecto=None),
    Movimiento(id=249, nombre='rock-smash', tipo='Lucha', power=40, accuracy=100, pp=15, generacion='Generation 2', categoria='físico', efecto='Inflicts regular damage with no additional effect. Can be used outside of battle to break rocks.', probabilidad_efecto=None),
    Movimiento(id=259, nombre='torment', tipo='Siniestro', power=None, accuracy=100, pp=15, generacion='Generation 3', categoria='estado', efecto='Prevents the target from using the same move twice in a row.', probabilidad_efecto=None),
    Movimiento(id=261, nombre='will-o-wisp', tipo='Fuego', power=None, accuracy=85, pp=15, generacion='Generation 3', categoria='estado', efecto='Burns the target.', probabilidad_efecto=None),
    Movimiento(id=263, nombre='facade', tipo='Normal', power=70, accuracy=100, pp=20, generacion='Generation 3', categoria='físico', efecto='Power doubles if user is burned, paralyzed, or poisoned.', probabilidad_efecto=None),
    Movimiento(id=264, nombre='focus-punch', tipo='Lucha', power=150, accuracy=100, pp=20, generacion='Generation 3', categoria='físico', efecto='If the user takes damage before attacking, the attack is canceled.', probabilidad_efecto=None),
    Movimiento(id=269, nombre='taunt', tipo='Siniestro', power=None, accuracy=100, pp=20, generacion='Generation 3', categoria='estado', efecto='For the next few turns, the target can only use damaging moves.', probabilidad_efecto=None),
    Movimiento(id=280, nombre='brick-break', tipo='Lucha', power=75, accuracy=100, pp=15, generacion='Generation 3', categoria='físico', efecto='Destroys Reflect and Light Screen.', probabilidad_efecto=None),
    Movimiento(id=290, nombre='secret-power', tipo='Normal', power=70, accuracy=100, pp=20, generacion='Generation 3', categoria='físico', efecto='Has a $effect_chance% chance to inflict a status effect which depends upon the terrain.', probabilidad_efecto=30),
    Movimiento(id=307, nombre='blast-burn', tipo='Fuego', power=150, accuracy=90, pp=5, generacion='Generation 3', categoria='especial', efecto='User foregoes its next turn to recharge.', probabilidad_efecto=None),
    Movimiento(id=315, nombre='overheat', tipo='Fuego', power=130, accuracy=90, pp=5, generacion='Generation 3', categoria='especial', efecto="Lowers the user's Special Attack by two stages after inflicting damage.", probabilidad_efecto=100),
    Movimiento(id=317, nombre='rock-tomb', tipo='Roca', power=60, accuracy=95, pp=15, generacion='Generation 3', categoria='físico', efecto="Has a $effect_chance% chance to lower the target's Speed by one stage.", probabilidad_efecto=100),
    Movimiento(id=332, nombre='aerial-ace', tipo='Volador', power=60, accuracy=None, pp=20, generacion='Generation 3', categoria='físico', efecto='Never misses.', probabilidad_efecto=None),
    Movimiento(id=339, nombre='bulk-up', tipo='Lucha', power=None, accuracy=None, pp=20, generacion='Generation 3', categoria='estado', efecto="Raises the user's Attack and Defense by one stage.", probabilidad_efecto=None),
    Movimiento(id=347, nombre='calm-mind', tipo='Psíquico', power=None, accuracy=None, pp=20, generacion='Generation 3', categoria='estado', efecto="Raises the user's Special Attack and Special Defense by one stage.", probabilidad_efecto=None),
    Movimiento(id=363, nombre='natural-gift', tipo='Normal', power=None, accuracy=100, pp=15, generacion='Generation 4', categoria='físico', efecto='Power and type depend on the held berry.', probabilidad_efecto=None),
    Movimiento(id=364, nombre='feint', tipo='Normal', power=30, accuracy=100, pp=10, generacion='Generation 4', categoria='físico', efecto='Hits through Protect and Detect.', probabilidad_efecto=None),
    Movimiento(id=369, nombre='u-turn', tipo='Bicho', power=70, accuracy=100, pp=20, generacion='Generation 4', categoria='físico', efecto='User must switch out after attacking.', probabilidad_efecto=None),
    Movimiento(id=370, nombre='close-combat', tipo='Lucha', power=120, accuracy=100, pp=5, generacion='Generation 4', categoria='físico', efecto="Lowers the user's Defense and Special Defense by one stage after inflicting damage.", probabilidad_efecto=100),
    Movimiento(id=374, nombre='fling', tipo='Siniestro', power=None, accuracy=100, pp=10, generacion='Generation 4', categoria='físico', efecto='Throws held item at the target; power depends on the item.', probabilidad_efecto=None),
    Movimiento(id=386, nombre='punishment', tipo='Siniestro', power=None, accuracy=100, pp=5, generacion='Generation 4', categoria='físico', efecto='Power increases against targets with more raised stats, up to a maximum of 200.', probabilidad_efecto=None),
    Movimiento(id=394, nombre='flare-blitz', tipo='Fuego', power=120, accuracy=100, pp=15, generacion='Generation 4', categoria='físico', efecto='User takes 1/3 the damage inflicted in recoil.  Has a $effect_chance% chance to [burn]{mechanic:burn} the target.', probabilidad_efecto=10),
    Movimiento(id=398, nombre='poison-jab', tipo='Veneno', power=80, accuracy=100, pp=20, generacion='Generation 4', categoria='físico', efecto='Has a $effect_chance% chance to [poison]{mechanic:poison} the target.', probabilidad_efecto=30),
    Movimiento(id=411, nombre='focus-blast', tipo='Lucha', power=120, accuracy=70, pp=5, generacion='Generation 4', categoria='especial', efecto="Has a $effect_chance% chance to lower the target's Special Defense by one stage.", probabilidad_efecto=10),
    Movimiento(id=416, nombre='giga-impact', tipo='Normal', power=150, accuracy=90, pp=5, generacion='Generation 4', categoria='físico', efecto='User foregoes its next turn to recharge.', probabilidad_efecto=None),
    Movimiento(id=421, nombre='shadow-claw', tipo='Fantasma', power=70, accuracy=100, pp=15, generacion='Generation 4', categoria='físico', efecto='Has an increased chance for a critical hit.', probabilidad_efecto=None),
    Movimiento(id=431, nombre='rock-climb', tipo='Normal', power=90, accuracy=85, pp=20, generacion='Generation 4', categoria='físico', efecto='Has a $effect_chance% chance to confuse the target.', probabilidad_efecto=20),
    Movimiento(id=444, nombre='stone-edge', tipo='Roca', power=100, accuracy=80, pp=5, generacion='Generation 4', categoria='físico', efecto='Has an increased chance for a critical hit.', probabilidad_efecto=None),
    Movimiento(id=445, nombre='captivate', tipo='Normal', power=None, accuracy=100, pp=20, generacion='Generation 4', categoria='estado', efecto="Lowers the target's Special Attack by two stages if it's the opposite gender.", probabilidad_efecto=None),
    Movimiento(id=446, nombre='stealth-rock', tipo='Roca', power=None, accuracy=None, pp=20, generacion='Generation 4', categoria='estado', efecto='Causes damage when opposing Pokémon switch in.', probabilidad_efecto=None),
    Movimiento(id=447, nombre='grass-knot', tipo='Planta', power=None, accuracy=100, pp=20, generacion='Generation 4', categoria='especial', efecto='Inflicts more damage to heavier targets, with a maximum of 120 power.', probabilidad_efecto=None),
    Movimiento(id=7, nombre='fire-punch', tipo='Fuego', power=75, accuracy=100, pp=15, generacion='Generation 1', categoria='físico', efecto='Has a $effect_chance% chance to [burn]{mechanic:burn} the target.', probabilidad_efecto=10),
    Movimiento(id=9, nombre='thunder-punch', tipo='Eléctrico', power=75, accuracy=100, pp=15, generacion='Generation 1', categoria='físico', efecto='Has a $effect_chance% chance to [paralyze]{mechanic:paralysis} the target.', probabilidad_efecto=10),
    Movimiento(id=129, nombre='swift', tipo='Normal', power=60, accuracy=None, pp=20, generacion='Generation 1', categoria='especial', efecto='Never misses.', probabilidad_efecto=None),
    Movimiento(id=173, nombre='snore', tipo='Normal', power=50, accuracy=100, pp=15, generacion='Generation 2', categoria='especial', efecto='Has a $effect_chance% chance to make the target flinch. Only works if the user is sleeping.', probabilidad_efecto=30),
    Movimiento(id=189, nombre='mud-slap', tipo='Tierra', power=20, accuracy=100, pp=10, generacion='Generation 2', categoria='especial', efecto="Has a $effect_chance% chance to lower the target's accuracy by one stage.", probabilidad_efecto=100),
    Movimiento(id=205, nombre='rollout', tipo='Roca', power=30, accuracy=90, pp=20, generacion='Generation 2', categoria='físico', efecto='Power doubles every turn this move is used in succession after the first, resetting after five turns.', probabilidad_efecto=None),
    Movimiento(id=257, nombre='heat-wave', tipo='Fuego', power=95, accuracy=90, pp=10, generacion='Generation 3', categoria='especial', efecto='Has a $effect_chance% chance to [burn]{mechanic:burn} the target.', probabilidad_efecto=10),
    Movimiento(id=270, nombre='helping-hand', tipo='Normal', power=None, accuracy=None, pp=20, generacion='Generation 3', categoria='estado', efecto="Ally's next move inflicts half more damage.", probabilidad_efecto=None),
    Movimiento(id=283, nombre='endeavor', tipo='Normal', power=None, accuracy=100, pp=5, generacion='Generation 3', categoria='físico', efecto="Lowers the target's HP to equal the user's.", probabilidad_efecto=None),
    Movimiento(id=410, nombre='vacuum-wave', tipo='Lucha', power=40, accuracy=100, pp=30, generacion='Generation 4', categoria='especial', efecto='Inflicts regular damage with no additional effect.', probabilidad_efecto=None),
    Movimiento(id=441, nombre='gunk-shot', tipo='Veneno', power=120, accuracy=80, pp=5, generacion='Generation 4', categoria='físico', efecto='Has a $effect_chance% chance to [poison]{mechanic:poison} the target.', probabilidad_efecto=30),
    Movimiento(id=29, nombre='headbutt', tipo='Normal', power=70, accuracy=100, pp=15, generacion='Generation 1', categoria='físico', efecto='Has a $effect_chance% chance to make the target flinch.', probabilidad_efecto=30),
    Movimiento(id=67, nombre='low-kick', tipo='Lucha', power=None, accuracy=100, pp=20, generacion='Generation 1', categoria='físico', efecto='Inflicts more damage to heavier targets, with a maximum of 120 power.', probabilidad_efecto=None),
    Movimiento(id=272, nombre='role-play', tipo='Psíquico', power=None, accuracy=None, pp=10, generacion='Generation 3', categoria='estado', efecto="Copies the target's ability.", probabilidad_efecto=None),
    Movimiento(id=468, nombre='hone-claws', tipo='Siniestro', power=None, accuracy=None, pp=15, generacion='Generation 5', categoria='estado', efecto="Raises the user's Attack and accuracy by one stage.", probabilidad_efecto=None),
    Movimiento(id=488, nombre='flame-charge', tipo='Fuego', power=50, accuracy=100, pp=20, generacion='Generation 5', categoria='físico', efecto="Inflicts regular damage. Raises the user's Speed by one stage.", probabilidad_efecto=100),
    Movimiento(id=490, nombre='low-sweep', tipo='Lucha', power=65, accuracy=100, pp=20, generacion='Generation 5', categoria='físico', efecto="Lowers the target's Speed by one stage.", probabilidad_efecto=100),
    Movimiento(id=496, nombre='round', tipo='Normal', power=60, accuracy=100, pp=15, generacion='Generation 5', categoria='especial', efecto="Has double power if it's used more than once per turn.", probabilidad_efecto=None),
    Movimiento(id=510, nombre='incinerate', tipo='Fuego', power=60, accuracy=100, pp=15, generacion='Generation 5', categoria='especial', efecto="Destroys the target's held berry.", probabilidad_efecto=None),
    Movimiento(id=512, nombre='acrobatics', tipo='Volador', power=55, accuracy=100, pp=15, generacion='Generation 5', categoria='físico', efecto='Has double power if the user has no held item.', probabilidad_efecto=None),
    Movimiento(id=514, nombre='retaliate', tipo='Normal', power=70, accuracy=100, pp=5, generacion='Generation 5', categoria='físico', efecto='Has double power if a friendly Pokémon fainted last turn.', probabilidad_efecto=None),
    Movimiento(id=519, nombre='fire-pledge', tipo='Fuego', power=80, accuracy=100, pp=10, generacion='Generation 5', categoria='especial', efecto="With [Water Pledge]{move:water-pledge}, doubles the effect chance of friendly Pokémon's moves for four turns.", probabilidad_efecto=None),
    Movimiento(id=523, nombre='bulldoze', tipo='Tierra', power=60, accuracy=100, pp=20, generacion='Generation 5', categoria='físico', efecto="Has a $effect_chance% chance to lower the target's Speed by one stage.", probabilidad_efecto=100),
    Movimiento(id=526, nombre='work-up', tipo='Normal', power=None, accuracy=None, pp=30, generacion='Generation 5', categoria='estado', efecto="Raises the user's Attack and Special Attack by one stage each.", probabilidad_efecto=None),
    Movimiento(id=343, nombre='covet', tipo='Normal', power=60, accuracy=100, pp=25, generacion='Generation 3', categoria='físico', efecto="Takes the target's item.", probabilidad_efecto=None),
    Movimiento(id=530, nombre='dual-chop', tipo='Dragón', power=40, accuracy=90, pp=15, generacion='Generation 5', categoria='físico', efecto='Hits twice in one turn.', probabilidad_efecto=None),
    Movimiento(id=590, nombre='confide', tipo='Normal', power=None, accuracy=None, pp=20, generacion='Generation 6', categoria='estado', efecto='User learns the target’s ability.', probabilidad_efecto=None),
    Movimiento(id=612, nombre='power-up-punch', tipo='Lucha', power=40, accuracy=100, pp=20, generacion='Generation 6', categoria='físico', efecto="Raises the user's Attack by one stage after inflicting damage.", probabilidad_efecto=100),
    Movimiento(id=673, nombre='laser-focus', tipo='Normal', power=None, accuracy=None, pp=30, generacion='Generation 7', categoria='estado', efecto="Guarantees a critical hit with the user's next move.", probabilidad_efecto=None)
]