from models import Movimiento

# ---------------------- JSON NATURES ----------------
nature_1 = {
    "id": 1,
    "nombre": "hardy",
    "aumenta_estadistica": "attack",
    "reduce_estadistica": "attack",
}

nature_2 = {
    "id": 2,
    "nombre": "bold",
    "aumenta_estadistica": "defense",
    "reduce_estadistica": "attack",
}
nature_3 = {
    "id": 3,
    "nombre": "modest",
    "aumenta_estadistica": "special-attack",
    "reduce_estadistica": "attack",
}
# ----------------- JSONS EQUIPOS --------------------------------
equipo_con_6_pokemons = {
    "id_equipo": 12,
    "nombre": "Equipo Elite",
}
equipo_siete_pokemons = {
    "id_equipo": 2,
    "nombre": "Equipo Sobrecargado",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                }
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 4,
            "nombre": "Gyarados",
            "naturaleza": {
                "id": 7,
                "nombre": "Bashful",
                "aumenta_estadistica": "Defensa",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 8,
                    "nombre": "Tierra",
                    "tipo": "Tierra",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "IV",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo_mismo_id = {
    "id_equipo": 1,
    "nombre": "Equipo Filete",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo = {
    "id_equipo": 2,
    "nombre": "Equipo Elite",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}

# ------------------------ JSONS POKEMONS -----------------------------

infernape_mock = {
        "pokemon_id": 392,
        "nombre": "infernape",
        "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/392.png",
        "tipos": ["Lucha", "Fuego"],
        "habilidades": ["Mar Llamas", "Puño Férreo"],
        'movimientos_ids': [10,
                     14,
                     15,
                     43,
                     46,
                     52,
                     53,
                     63,
                     70,
                     76,
                     83,
                     89,
                     91,
                     92,
                     104,
                     126,
                     154,
                     156,
                     157,
                     164,
                     172,
                     182,
                     183,
                     203,
                     207,
                     213,
                     214,
                     216,
                     218,
                     231,
                     237,
                     241,
                     249,
                     259,
                     261,
                     263,
                     264,
                     269,
                     280,
                     290,
                     307,
                     315,
                     317,
                     332,
                     339,
                     347,
                     363,
                     364,
                     369,
                     370,
                     374,
                     386,
                     394,
                     398,
                     411,
                     416,
                     421,
                     431,
                     444,
                     445,
                     446,
                     447,
                     7,
                     9,
                     129,
                     173,
                     189,
                     205,
                     257,
                     270,
                     283,
                     410,
                     441,
                     29,
                     67,
                     272,
                     468,
                     488,
                     490,
                     496,
                     510,
                     512,
                     514,
                     519,
                     523,
                     526,
                     343,
                     530,
                     590,
                     612,
                     673],
        "altura": 12,
        "peso": 550,
        "estadisticas": {
            "hp": 76,
            "attack": 104,
            "defense": 71,
            "special-attack": 104,
            "special-defense": 71,
            "speed": 108,
            "accuracy": 0,
            "evasion": 0,
        },
        "cadena_evolutiva_ids": [390, 391, 392],
    }

movimientos_infernape = [{'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Inflicts regular damage with no additional effect.',
  'generacion': 'Generation 1',
  'id': 10,
  'nombre': 'scratch',
  'power': 40,
  'pp': 35,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Raises the user's Attack by two stages.",
  'generacion': 'Generation 1',
  'id': 14,
  'nombre': 'swords-dance',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 95,
  'categoria': 'físico',
  'efecto': 'Inflicts regular damage with no additional effect.',
  'generacion': 'Generation 1',
  'id': 15,
  'nombre': 'cut',
  'power': 50,
  'pp': 30,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'estado',
  'efecto': "Lowers the target's Defense by one stage.",
  'generacion': 'Generation 1',
  'id': 43,
  'nombre': 'leer',
  'power': None,
  'pp': 30,
  'probabilidad_efecto': 100,
  'tipo': 'Normal'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': 'Immediately ends wild battles.  Forces trainers to switch '
            'Pokémon.',
  'generacion': 'Generation 1',
  'id': 46,
  'nombre': 'roar',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': 'Has a $effect_chance% chance to [burn]{mechanic:burn} the target.',
  'generacion': 'Generation 1',
  'id': 52,
  'nombre': 'ember',
  'power': 40,
  'pp': 25,
  'probabilidad_efecto': 10,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': 'Has a $effect_chance% chance to [burn]{mechanic:burn} the target.',
  'generacion': 'Generation 1',
  'id': 53,
  'nombre': 'flamethrower',
  'power': 90,
  'pp': 15,
  'probabilidad_efecto': 10,
  'tipo': 'Fuego'},
 {'accuracy': 90,
  'categoria': 'especial',
  'efecto': 'User foregoes its next turn to recharge.',
  'generacion': 'Generation 1',
  'id': 63,
  'nombre': 'hyper-beam',
  'power': 150,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Inflicts regular damage with no additional effect.',
  'generacion': 'Generation 1',
  'id': 70,
  'nombre': 'strength',
  'power': 80,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': 'Requires a turn to charge before attacking.',
  'generacion': 'Generation 1',
  'id': 76,
  'nombre': 'solar-beam',
  'power': 120,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Planta'},
 {'accuracy': 85,
  'categoria': 'especial',
  'efecto': 'Prevents the target from fleeing and inflicts damage for 2-5 '
            'turns.',
  'generacion': 'Generation 1',
  'id': 83,
  'nombre': 'fire-spin',
  'power': 35,
  'pp': 15,
  'probabilidad_efecto': 100,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Inflicts regular damage and can hit Dig users.',
  'generacion': 'Generation 1',
  'id': 89,
  'nombre': 'earthquake',
  'power': 100,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Tierra'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'User digs underground, dodging all attacks, and hits next turn.',
  'generacion': 'Generation 1',
  'id': 91,
  'nombre': 'dig',
  'power': 80,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Tierra'},
 {'accuracy': 90,
  'categoria': 'estado',
  'efecto': 'Badly poisons the target, inflicting more damage every turn.',
  'generacion': 'Generation 1',
  'id': 92,
  'nombre': 'toxic',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Veneno'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Raises the user's evasion by one stage.",
  'generacion': 'Generation 1',
  'id': 104,
  'nombre': 'double-team',
  'power': None,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 85,
  'categoria': 'especial',
  'efecto': 'Has a $effect_chance% chance to [burn]{mechanic:burn} the target.',
  'generacion': 'Generation 1',
  'id': 126,
  'nombre': 'fire-blast',
  'power': 110,
  'pp': 5,
  'probabilidad_efecto': 10,
  'tipo': 'Fuego'},
 {'accuracy': 80,
  'categoria': 'físico',
  'efecto': 'Hits 2-5 times in one turn.',
  'generacion': 'Generation 1',
  'id': 154,
  'nombre': 'fury-swipes',
  'power': 18,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': 'User sleeps for two turns, completely healing itself.',
  'generacion': 'Generation 1',
  'id': 156,
  'nombre': 'rest',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Psíquico'},
 {'accuracy': 90,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to make the target flinch.',
  'generacion': 'Generation 1',
  'id': 157,
  'nombre': 'rock-slide',
  'power': 75,
  'pp': 10,
  'probabilidad_efecto': 30,
  'tipo': 'Roca'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Transfers 1/4 of the user's max HP into a doll, protecting the "
            'user from further damage or status changes until it breaks.',
  'generacion': 'Generation 1',
  'id': 164,
  'nombre': 'substitute',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to [burn]{mechanic:burn} the '
            'target.  Lets frozen Pokémon thaw themselves.',
  'generacion': 'Generation 2',
  'id': 172,
  'nombre': 'flame-wheel',
  'power': 60,
  'pp': 25,
  'probabilidad_efecto': 10,
  'tipo': 'Fuego'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': 'Prevents any moves from hitting the user this turn.',
  'generacion': 'Generation 2',
  'id': 182,
  'nombre': 'protect',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Inflicts regular damage with no additional effect.',
  'generacion': 'Generation 2',
  'id': 183,
  'nombre': 'mach-punch',
  'power': 40,
  'pp': 30,
  'probabilidad_efecto': None,
  'tipo': 'Lucha'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Prevents the user's HP from lowering below 1 this turn.",
  'generacion': 'Generation 2',
  'id': 203,
  'nombre': 'endure',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 85,
  'categoria': 'estado',
  'efecto': "Raises the target's Attack by two stages and confuses the target.",
  'generacion': 'Generation 2',
  'id': 207,
  'nombre': 'swagger',
  'power': None,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'estado',
  'efecto': 'Target falls in love if it has the opposite gender, and has a 50% '
            'chance to refuse attacking the user.',
  'generacion': 'Generation 2',
  'id': 213,
  'nombre': 'attract',
  'power': None,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Randomly uses one of the user's other three moves.  Only works if "
            'the user is sleeping.',
  'generacion': 'Generation 2',
  'id': 214,
  'nombre': 'sleep-talk',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Power increases with happiness, up to a maximum of 102.',
  'generacion': 'Generation 2',
  'id': 216,
  'nombre': 'return',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Power increases as happiness decreases, up to a maximum of 102.',
  'generacion': 'Generation 2',
  'id': 218,
  'nombre': 'frustration',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 75,
  'categoria': 'físico',
  'efecto': "Has a $effect_chance% chance to lower the target's Defense by one "
            'stage.',
  'generacion': 'Generation 2',
  'id': 231,
  'nombre': 'iron-tail',
  'power': 100,
  'pp': 15,
  'probabilidad_efecto': 30,
  'tipo': 'Acero'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': "Power and type depend upon user's IVs.  Power can range from 30 "
            'to 70.',
  'generacion': 'Generation 2',
  'id': 237,
  'nombre': 'hidden-power',
  'power': 60,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': 'Changes the weather to sunny for five turns.',
  'generacion': 'Generation 2',
  'id': 241,
  'nombre': 'sunny-day',
  'power': None,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Has a $effect_chance% chance to lower the target's Defense by one "
            'stage.',
  'generacion': 'Generation 2',
  'id': 249,
  'nombre': 'rock-smash',
  'power': 40,
  'pp': 15,
  'probabilidad_efecto': 50,
  'tipo': 'Lucha'},
 {'accuracy': 100,
  'categoria': 'estado',
  'efecto': 'Prevents the target from using the same move twice in a row.',
  'generacion': 'Generation 3',
  'id': 259,
  'nombre': 'torment',
  'power': None,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Siniestro'},
 {'accuracy': 85,
  'categoria': 'estado',
  'efecto': 'Burns the target.',
  'generacion': 'Generation 3',
  'id': 261,
  'nombre': 'will-o-wisp',
  'power': None,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Power doubles if user is burned, paralyzed, or poisoned.',
  'generacion': 'Generation 3',
  'id': 263,
  'nombre': 'facade',
  'power': 70,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'If the user takes damage before attacking, the attack is '
            'canceled.',
  'generacion': 'Generation 3',
  'id': 264,
  'nombre': 'focus-punch',
  'power': 150,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Lucha'},
 {'accuracy': 100,
  'categoria': 'estado',
  'efecto': 'For the next few turns, the target can only use damaging moves.',
  'generacion': 'Generation 3',
  'id': 269,
  'nombre': 'taunt',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Siniestro'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Destroys Reflect and Light Screen.',
  'generacion': 'Generation 3',
  'id': 280,
  'nombre': 'brick-break',
  'power': 75,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Lucha'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to inflict a status effect which '
            'depends upon the terrain.',
  'generacion': 'Generation 3',
  'id': 290,
  'nombre': 'secret-power',
  'power': 70,
  'pp': 20,
  'probabilidad_efecto': 30,
  'tipo': 'Normal'},
 {'accuracy': 90,
  'categoria': 'especial',
  'efecto': 'User foregoes its next turn to recharge.',
  'generacion': 'Generation 3',
  'id': 307,
  'nombre': 'blast-burn',
  'power': 150,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Fuego'},
 {'accuracy': 90,
  'categoria': 'especial',
  'efecto': "Lowers the user's Special Attack by two stages after inflicting "
            'damage.',
  'generacion': 'Generation 3',
  'id': 315,
  'nombre': 'overheat',
  'power': 130,
  'pp': 5,
  'probabilidad_efecto': 100,
  'tipo': 'Fuego'},
 {'accuracy': 95,
  'categoria': 'físico',
  'efecto': "Has a $effect_chance% chance to lower the target's Speed by one "
            'stage.',
  'generacion': 'Generation 3',
  'id': 317,
  'nombre': 'rock-tomb',
  'power': 60,
  'pp': 15,
  'probabilidad_efecto': 100,
  'tipo': 'Roca'},
 {'accuracy': None,
  'categoria': 'físico',
  'efecto': 'Never misses.',
  'generacion': 'Generation 3',
  'id': 332,
  'nombre': 'aerial-ace',
  'power': 60,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Volador'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Raises the user's Attack and Defense by one stage.",
  'generacion': 'Generation 3',
  'id': 339,
  'nombre': 'bulk-up',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Lucha'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Raises the user's Special Attack and Special Defense by one "
            'stage.',
  'generacion': 'Generation 3',
  'id': 347,
  'nombre': 'calm-mind',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Psíquico'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Power and type depend on the held berry.',
  'generacion': 'Generation 4',
  'id': 363,
  'nombre': 'natural-gift',
  'power': None,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Hits through Protect and Detect.',
  'generacion': 'Generation 4',
  'id': 364,
  'nombre': 'feint',
  'power': 30,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'User must switch out after attacking.',
  'generacion': 'Generation 4',
  'id': 369,
  'nombre': 'u-turn',
  'power': 70,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Bicho'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Lowers the user's Defense and Special Defense by one stage after "
            'inflicting damage.',
  'generacion': 'Generation 4',
  'id': 370,
  'nombre': 'close-combat',
  'power': 120,
  'pp': 5,
  'probabilidad_efecto': 100,
  'tipo': 'Lucha'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Throws held item at the target; power depends on the item.',
  'generacion': 'Generation 4',
  'id': 374,
  'nombre': 'fling',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Siniestro'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Power increases against targets with more raised stats, up to a '
            'maximum of 200.',
  'generacion': 'Generation 4',
  'id': 386,
  'nombre': 'punishment',
  'power': None,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Siniestro'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'User takes 1/3 the damage inflicted in recoil.  Has a '
            '$effect_chance% chance to [burn]{mechanic:burn} the target.',
  'generacion': 'Generation 4',
  'id': 394,
  'nombre': 'flare-blitz',
  'power': 120,
  'pp': 15,
  'probabilidad_efecto': 10,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to [poison]{mechanic:poison} the '
            'target.',
  'generacion': 'Generation 4',
  'id': 398,
  'nombre': 'poison-jab',
  'power': 80,
  'pp': 20,
  'probabilidad_efecto': 30,
  'tipo': 'Veneno'},
 {'accuracy': 70,
  'categoria': 'especial',
  'efecto': "Has a $effect_chance% chance to lower the target's Special "
            'Defense by one stage.',
  'generacion': 'Generation 4',
  'id': 411,
  'nombre': 'focus-blast',
  'power': 120,
  'pp': 5,
  'probabilidad_efecto': 10,
  'tipo': 'Lucha'},
 {'accuracy': 90,
  'categoria': 'físico',
  'efecto': 'User foregoes its next turn to recharge.',
  'generacion': 'Generation 4',
  'id': 416,
  'nombre': 'giga-impact',
  'power': 150,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has an increased chance for a critical hit.',
  'generacion': 'Generation 4',
  'id': 421,
  'nombre': 'shadow-claw',
  'power': 70,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Fantasma'},
 {'accuracy': 85,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to confuse the target.',
  'generacion': 'Generation 4',
  'id': 431,
  'nombre': 'rock-climb',
  'power': 90,
  'pp': 20,
  'probabilidad_efecto': 20,
  'tipo': 'Normal'},
 {'accuracy': 80,
  'categoria': 'físico',
  'efecto': 'Has an increased chance for a critical hit.',
  'generacion': 'Generation 4',
  'id': 444,
  'nombre': 'stone-edge',
  'power': 100,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Roca'},
 {'accuracy': 100,
  'categoria': 'estado',
  'efecto': "Lowers the target's Special Attack by two stages if it's the "
            'opposite gender.',
  'generacion': 'Generation 4',
  'id': 445,
  'nombre': 'captivate',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': 'Causes damage when opposing Pokémon switch in.',
  'generacion': 'Generation 4',
  'id': 446,
  'nombre': 'stealth-rock',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Roca'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': 'Inflicts more damage to heavier targets, with a maximum of 120 '
            'power.',
  'generacion': 'Generation 4',
  'id': 447,
  'nombre': 'grass-knot',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Planta'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to [burn]{mechanic:burn} the target.',
  'generacion': 'Generation 1',
  'id': 7,
  'nombre': 'fire-punch',
  'power': 75,
  'pp': 15,
  'probabilidad_efecto': 10,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to [paralyze]{mechanic:paralysis} '
            'the target.',
  'generacion': 'Generation 1',
  'id': 9,
  'nombre': 'thunder-punch',
  'power': 75,
  'pp': 15,
  'probabilidad_efecto': 10,
  'tipo': 'Eléctrico'},
 {'accuracy': None,
  'categoria': 'especial',
  'efecto': 'Never misses.',
  'generacion': 'Generation 1',
  'id': 129,
  'nombre': 'swift',
  'power': 60,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': 'Has a $effect_chance% chance to make the target flinch.  Only '
            'works if the user is sleeping.',
  'generacion': 'Generation 2',
  'id': 173,
  'nombre': 'snore',
  'power': 50,
  'pp': 15,
  'probabilidad_efecto': 30,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': "Has a $effect_chance% chance to lower the target's accuracy by "
            'one stage.',
  'generacion': 'Generation 2',
  'id': 189,
  'nombre': 'mud-slap',
  'power': 20,
  'pp': 10,
  'probabilidad_efecto': 100,
  'tipo': 'Tierra'},
 {'accuracy': 90,
  'categoria': 'físico',
  'efecto': 'Power doubles every turn this move is used in succession after '
            'the first, resetting after five turns.',
  'generacion': 'Generation 2',
  'id': 205,
  'nombre': 'rollout',
  'power': 30,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Roca'},
 {'accuracy': 90,
  'categoria': 'especial',
  'efecto': 'Has a $effect_chance% chance to [burn]{mechanic:burn} the target.',
  'generacion': 'Generation 3',
  'id': 257,
  'nombre': 'heat-wave',
  'power': 95,
  'pp': 10,
  'probabilidad_efecto': 10,
  'tipo': 'Fuego'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Ally's next move inflicts half more damage.",
  'generacion': 'Generation 3',
  'id': 270,
  'nombre': 'helping-hand',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Lowers the target's HP to equal the user's.",
  'generacion': 'Generation 3',
  'id': 283,
  'nombre': 'endeavor',
  'power': None,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': 'Inflicts regular damage with no additional effect.',
  'generacion': 'Generation 4',
  'id': 410,
  'nombre': 'vacuum-wave',
  'power': 40,
  'pp': 30,
  'probabilidad_efecto': None,
  'tipo': 'Lucha'},
 {'accuracy': 80,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to [poison]{mechanic:poison} the '
            'target.',
  'generacion': 'Generation 4',
  'id': 441,
  'nombre': 'gunk-shot',
  'power': 120,
  'pp': 5,
  'probabilidad_efecto': 30,
  'tipo': 'Veneno'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has a $effect_chance% chance to make the target flinch.',
  'generacion': 'Generation 1',
  'id': 29,
  'nombre': 'headbutt',
  'power': 70,
  'pp': 15,
  'probabilidad_efecto': 30,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Inflicts more damage to heavier targets, with a maximum of 120 '
            'power.',
  'generacion': 'Generation 1',
  'id': 67,
  'nombre': 'low-kick',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': None,
  'tipo': 'Lucha'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Copies the target's ability.",
  'generacion': 'Generation 3',
  'id': 272,
  'nombre': 'role-play',
  'power': None,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Psíquico'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Raises the user's Attack and accuracy by one stage.",
  'generacion': 'Generation 5',
  'id': 468,
  'nombre': 'hone-claws',
  'power': None,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Siniestro'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Inflicts regular damage.  Raises the user's Speed by one stage.",
  'generacion': 'Generation 5',
  'id': 488,
  'nombre': 'flame-charge',
  'power': 50,
  'pp': 20,
  'probabilidad_efecto': 100,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Lowers the target's Speed by one stage.",
  'generacion': 'Generation 5',
  'id': 490,
  'nombre': 'low-sweep',
  'power': 65,
  'pp': 20,
  'probabilidad_efecto': 100,
  'tipo': 'Lucha'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': "Has double power if it's used more than once per turn.",
  'generacion': 'Generation 5',
  'id': 496,
  'nombre': 'round',
  'power': 60,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': "Destroys the target's held berry.",
  'generacion': 'Generation 5',
  'id': 510,
  'nombre': 'incinerate',
  'power': 60,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has double power if the user has no held item.',
  'generacion': 'Generation 5',
  'id': 512,
  'nombre': 'acrobatics',
  'power': 55,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Volador'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': 'Has double power if a friendly Pokémon fainted last turn.',
  'generacion': 'Generation 5',
  'id': 514,
  'nombre': 'retaliate',
  'power': 70,
  'pp': 5,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'especial',
  'efecto': 'With [Water Pledge]{move:water-pledge}, doubles the effect chance '
            "of friendly Pokémon's moves for four turns.",
  'generacion': 'Generation 5',
  'id': 519,
  'nombre': 'fire-pledge',
  'power': 80,
  'pp': 10,
  'probabilidad_efecto': None,
  'tipo': 'Fuego'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Has a $effect_chance% chance to lower the target's Speed by one "
            'stage.',
  'generacion': 'Generation 5',
  'id': 523,
  'nombre': 'bulldoze',
  'power': 60,
  'pp': 20,
  'probabilidad_efecto': 100,
  'tipo': 'Tierra'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Raises the user's Attack and Special Attack by one stage each.",
  'generacion': 'Generation 5',
  'id': 526,
  'nombre': 'work-up',
  'power': None,
  'pp': 30,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Takes the target's item.",
  'generacion': 'Generation 3',
  'id': 343,
  'nombre': 'covet',
  'power': 60,
  'pp': 25,
  'probabilidad_efecto': None,
  'tipo': 'Normal'},
 {'accuracy': 90,
  'categoria': 'físico',
  'efecto': 'Hits twice in one turn.',
  'generacion': 'Generation 5',
  'id': 530,
  'nombre': 'dual-chop',
  'power': 40,
  'pp': 15,
  'probabilidad_efecto': None,
  'tipo': 'Dragón'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Lowers the target's Special Attack by one stage.",
  'generacion': 'Generation 6',
  'id': 590,
  'nombre': 'confide',
  'power': None,
  'pp': 20,
  'probabilidad_efecto': 100,
  'tipo': 'Normal'},
 {'accuracy': 100,
  'categoria': 'físico',
  'efecto': "Raises the user's Attack by one stage after inflicting damage.",
  'generacion': 'Generation 6',
  'id': 612,
  'nombre': 'power-up-punch',
  'power': 40,
  'pp': 20,
  'probabilidad_efecto': 100,
  'tipo': 'Lucha'},
 {'accuracy': None,
  'categoria': 'estado',
  'efecto': "Guarantees a critical hit with the user's next move.",
  'generacion': 'Generation 7',
  'id': 673,
  'nombre': 'laser-focus',
  'power': None,
  'pp': 30,
  'probabilidad_efecto': None,
  'tipo': 'Normal'}]
