# ---------------------- JSON NATURES ----------------
nature_1 = {
    "id": 1,
    "nombre": "hardy",
    "aumenta_estadistica": "attack",
    "reduce_estadistica": "attack",
}

nature_2 = {
    "id": 2,
    "nombre": "bold",
    "aumenta_estadistica": "defense",
    "reduce_estadistica": "attack",
}
nature_3 = {
    "id": 3,
    "nombre": "modest",
    "aumenta_estadistica": "special-attack",
    "reduce_estadistica": "attack",
}
# ----------------- JSONS EQUIPOS --------------------------------
equipo_con_6_pokemons = {
    "id_equipo": 1,
    "nombre": "Equipo Elite",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo_siete_pokemons = {
    "id_equipo": 2,
    "nombre": "Equipo Sobrecargado",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                }
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 4,
            "nombre": "Gyarados",
            "naturaleza": {
                "id": 7,
                "nombre": "Bashful",
                "aumenta_estadistica": "Defensa",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 8,
                    "nombre": "Tierra",
                    "tipo": "Tierra",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "IV",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo_mismo_id = {
    "id_equipo": 1,
    "nombre": "Equipo Filete",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}
equipo = {
    "id_equipo": 2,
    "nombre": "Equipo Elite",
    "pokemons_de_equipo": [
        {
            "id": 25,
            "nombre": "Pikachu",
            "naturaleza": {
                "id": 1,
                "nombre": "Activa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 1,
                    "nombre": "Impactrueno",
                    "tipo": "Eléctrico",
                    "power": 40,
                    "accuracy": 100,
                    "pp": 30,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
                {
                    "id": 2,
                    "nombre": "Rayo",
                    "tipo": "Eléctrico",
                    "power": 90,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Parálisis",
                    "probabilidad_efecto": 10,
                },
            ],
        },
        {
            "id": 6,
            "nombre": "Charizard",
            "naturaleza": {
                "id": 2,
                "nombre": "Audaz",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 3,
                    "nombre": "Llamarada",
                    "tipo": "Fuego",
                    "power": 110,
                    "accuracy": 85,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Quemadura",
                    "probabilidad_efecto": 30,
                }
            ],
        },
        {
            "id": 9,
            "nombre": "Blastoise",
            "naturaleza": {
                "id": 3,
                "nombre": "Modesta",
                "aumenta_estadistica": "Ataque Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 4,
                    "nombre": "Hidrobomba",
                    "tipo": "Agua",
                    "power": 110,
                    "accuracy": 80,
                    "pp": 5,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 3,
            "nombre": "Venusaur",
            "naturaleza": {
                "id": 4,
                "nombre": "Serena",
                "aumenta_estadistica": "Defensa Especial",
                "reduce_estadistica": "Ataque",
            },
            "movimientos": [
                {
                    "id": 5,
                    "nombre": "Solar Rayo",
                    "tipo": "Planta",
                    "power": 120,
                    "accuracy": 100,
                    "pp": 10,
                    "generacion": "I",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 94,
            "nombre": "Gengar",
            "naturaleza": {
                "id": 5,
                "nombre": "Miedosa",
                "aumenta_estadistica": "Velocidad",
                "reduce_estadistica": "Defensa",
            },
            "movimientos": [
                {
                    "id": 6,
                    "nombre": "Bola Sombra",
                    "tipo": "Fantasma",
                    "power": 80,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Especial",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
        {
            "id": 149,
            "nombre": "Dragonite",
            "naturaleza": {
                "id": 6,
                "nombre": "Firme",
                "aumenta_estadistica": "Ataque",
                "reduce_estadistica": "Defensa Especial",
            },
            "movimientos": [
                {
                    "id": 7,
                    "nombre": "Puño Fuego",
                    "tipo": "Fuego",
                    "power": 100,
                    "accuracy": 100,
                    "pp": 15,
                    "generacion": "II",
                    "categoria": "Físico",
                    "efecto": "Ninguno",
                    "probabilidad_efecto": None,
                }
            ],
        },
    ],
}

# ------------------------ JSONS POKEMONS -----------------------------
movimientos_ids_infernape = [
10,14,15,43,46,52,53,63,70,76,83,89, 91, 92, 104, 126, 154, 156, 157, 164, 172, 182, 183, 203, 207, 213, 214, 216, 218, 231, 237, 241, 249, 259, 261, 263, 264, 269, 280, 290, 307, 315, 317, 332, 339, 347, 363, 364, 369, 370, 374, 386, 394,398,411,416,421,431,444,445,446,447,7,9,129,173,189,205,257,270,283,410,441,29, 67,272,468,488,490,496,510,512,514,519,523,526,343,530,590,612,673]

relaciones_infernape = relaciones = pokemon_movimientos = [{"pokemon_id": 392, "movimiento_id": movimiento_id} for movimiento_id in movimientos_ids_infernape]

infernape_mock = {
  "pokemon_id": 392,
  "nombre": "infernape",
  "imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/392.png",
  "tipos": [
    "Lucha",
    "Fuego"
  ],
  "habilidades": [
    "Mar Llamas",
    "Puño Férreo"
  ],
  "movimientos_ids": [
    10,
    14,
    15,
    43,
    46,
    52,
    53,
    63,
    70,
    76,
    83,
    89,
    91,
    92,
    104,
    126,
    154,
    156,
    157,
    164,
    172,
    182,
    183,
    203,
    207,
    213,
    214,
    216,
    218,
    231,
    237,
    241,
    249,
    259,
    261,
    263,
    264,
    269,
    280,
    290,
    307,
    315,
    317,
    332,
    339,
    347,
    363,
    364,
    369,
    370,
    374,
    386,
    394,
    398,
    411,
    416,
    421,
    431,
    444,
    445,
    446,
    447,
    7,
    9,
    129,
    173,
    189,
    205,
    257,
    270,
    283,
    410,
    441,
    29,
    67,
    272,
    468,
    488,
    490,
    496,
    510,
    512,
    514,
    519,
    523,
    526,
    343,
    530,
    590,
    612,
    673
  ],
  "altura": 12,
  "peso": 550,
  "estadisticas": {
    "hp": 76,
    "attack": 104,
    "defense": 71,
    "special-attack": 104,
    "special-defense": 71,
    "speed": 108,
    "accuracy": 0,
    "evasion": 0
  },
  "cadena_evolutiva_ids": [
    390,
    391,
    392
  ]
}
infernape_nuevo_modelo = {
        "id": 392,
        "nombre": "infernape",
        "url_imagen": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/392.png",
        "tipo_1": "Lucha",
        "tipo_2": "Fuego",
        "habilidad_1": "Mar Llamas",
        "habilidad_2": "Puño Férreo",
        "habilidad_3": None,
        "altura": 12,
        "peso": 550,
        "estadistica_hp": 76,
        "estadistica_attack": 104,
        "estadistica_defense": 71,
        "estadistica_special_attack": 104,
        "estadistica_special_defense": 71,
        "estadistica_speed": 108,
        "id_evolucion_anterior": 391,
        "id_evolucion_siguiente": None
    }

movimientos_infernape = [
  {
    "nombre": "Puño Fuego",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": 10,
    "tipo": "Fuego",
    "power": 75,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to [burn]{mechanic:burn} the target.",
    "id": 7
  },
  {
    "nombre": "Puño Trueno",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": 10,
    "tipo": "Eléctrico",
    "power": 75,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to [paralyze]{mechanic:paralysis} the target.",
    "id": 9
  },
  {
    "nombre": "Arañazo",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 40,
    "pp": 35,
    "efecto": "Inflicts regular damage with no additional effect.",
    "id": 10
  },
  {
    "nombre": "Danza Espada",
    "accuracy": None,
    "generacion": "Generación 1",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 20,
    "efecto": "Raises the user's Attack by two stages.",
    "id": 14
  },
  {
    "nombre": "Corte",
    "accuracy": 95,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 50,
    "pp": 30,
    "efecto": "Inflicts regular damage with no additional effect.",
    "id": 15
  },
  {
    "nombre": "Golpe Cabeza",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": 30,
    "tipo": "Normal",
    "power": 70,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to make the target flinch.",
    "id": 29
  },
  {
    "nombre": "Malicioso",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "estado",
    "probabilidad_efecto": 100,
    "tipo": "Normal",
    "power": None,
    "pp": 30,
    "efecto": "Lowers the target's Defense by one stage.",
    "id": 43
  },
  {
    "nombre": "Rugido",
    "accuracy": None,
    "generacion": "Generación 1",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 20,
    "efecto": "Immediately ends wild battles.  Forces trainers to switch Pokémon.",
    "id": 46
  },
  {
    "nombre": "Ascuas",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "especial",
    "probabilidad_efecto": 10,
    "tipo": "Fuego",
    "power": 40,
    "pp": 25,
    "efecto": "Has a $effect_chance% chance to [burn]{mechanic:burn} the target.",
    "id": 52
  },
  {
    "nombre": "Lanzallamas",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "especial",
    "probabilidad_efecto": 10,
    "tipo": "Fuego",
    "power": 90,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to [burn]{mechanic:burn} the target.",
    "id": 53
  },
  {
    "nombre": "Hiperrayo",
    "accuracy": 90,
    "generacion": "Generación 1",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 150,
    "pp": 5,
    "efecto": "User foregoes its next turn to recharge.",
    "id": 63
  },
  {
    "nombre": "Patada Baja",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Lucha",
    "power": None,
    "pp": 20,
    "efecto": "Inflicts more damage to heavier targets, with a maximum of 120 power.",
    "id": 67
  },
  {
    "nombre": "Fuerza",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 80,
    "pp": 15,
    "efecto": "Inflicts regular damage with no additional effect.",
    "id": 70
  },
  {
    "nombre": "Rayo Solar",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Planta",
    "power": 120,
    "pp": 10,
    "efecto": "Requires a turn to charge before attacking.",
    "id": 76
  },
  {
    "nombre": "Giro Fuego",
    "accuracy": 85,
    "generacion": "Generación 1",
    "categoria": "especial",
    "probabilidad_efecto": 100,
    "tipo": "Fuego",
    "power": 35,
    "pp": 15,
    "efecto": "Prevents the target from fleeing and inflicts damage for 2-5 turns.",
    "id": 83
  },
  {
    "nombre": "Terremoto",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Tierra",
    "power": 100,
    "pp": 10,
    "efecto": "Inflicts regular damage and can hit Dig users.",
    "id": 89
  },
  {
    "nombre": "Excavar",
    "accuracy": 100,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Tierra",
    "power": 80,
    "pp": 10,
    "efecto": "User digs underground, dodging all attacks, and hits next turn.",
    "id": 91
  },
  {
    "nombre": "Tóxico",
    "accuracy": 90,
    "generacion": "Generación 1",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Veneno",
    "power": None,
    "pp": 10,
    "efecto": "Badly poisons the target, inflicting more damage every turn.",
    "id": 92
  },
  {
    "nombre": "Doble Equipo",
    "accuracy": None,
    "generacion": "Generación 1",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 15,
    "efecto": "Raises the user's evasion by one stage.",
    "id": 104
  },
  {
    "nombre": "Llamarada",
    "accuracy": 85,
    "generacion": "Generación 1",
    "categoria": "especial",
    "probabilidad_efecto": 10,
    "tipo": "Fuego",
    "power": 110,
    "pp": 5,
    "efecto": "Has a $effect_chance% chance to [burn]{mechanic:burn} the target.",
    "id": 126
  },
  {
    "nombre": "Rapidez",
    "accuracy": None,
    "generacion": "Generación 1",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 60,
    "pp": 20,
    "efecto": "Never misses.",
    "id": 129
  },
  {
    "nombre": "Golpes Furia",
    "accuracy": 80,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 18,
    "pp": 15,
    "efecto": "Hits 2-5 times in one turn.",
    "id": 154
  },
  {
    "nombre": "Descanso",
    "accuracy": None,
    "generacion": "Generación 1",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Psíquico",
    "power": None,
    "pp": 10,
    "efecto": "User sleeps for two turns, completely healing itself.",
    "id": 156
  },
  {
    "nombre": "Avalancha",
    "accuracy": 90,
    "generacion": "Generación 1",
    "categoria": "físico",
    "probabilidad_efecto": 30,
    "tipo": "Roca",
    "power": 75,
    "pp": 10,
    "efecto": "Has a $effect_chance% chance to make the target flinch.",
    "id": 157
  },
  {
    "nombre": "Sustituto",
    "accuracy": None,
    "generacion": "Generación 1",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 10,
    "efecto": "Transfers 1/4 of the user's max HP into a doll, protecting the user from further damage or status changes until it breaks.",
    "id": 164
  },
  {
    "nombre": "Rueda Fuego",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "físico",
    "probabilidad_efecto": 10,
    "tipo": "Fuego",
    "power": 60,
    "pp": 25,
    "efecto": "Has a $effect_chance% chance to [burn]{mechanic:burn} the target.  Lets frozen Pokémon thaw themselves.",
    "id": 172
  },
  {
    "nombre": "Ronquido",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "especial",
    "probabilidad_efecto": 30,
    "tipo": "Normal",
    "power": 50,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to make the target flinch.  Only works if the user is sleeping.",
    "id": 173
  },
  {
    "nombre": "Protección",
    "accuracy": None,
    "generacion": "Generación 2",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 10,
    "efecto": "Prevents any moves from hitting the user this turn.",
    "id": 182
  },
  {
    "nombre": "Ultrapuño",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Lucha",
    "power": 40,
    "pp": 30,
    "efecto": "Inflicts regular damage with no additional effect.",
    "id": 183
  },
  {
    "nombre": "Bofetón Lodo",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "especial",
    "probabilidad_efecto": 100,
    "tipo": "Tierra",
    "power": 20,
    "pp": 10,
    "efecto": "Has a $effect_chance% chance to lower the target's accuracy by one stage.",
    "id": 189
  },
  {
    "nombre": "Aguante",
    "accuracy": None,
    "generacion": "Generación 2",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 10,
    "efecto": "Prevents the user's HP from lowering below 1 this turn.",
    "id": 203
  },
  {
    "nombre": "Rodar",
    "accuracy": 90,
    "generacion": "Generación 2",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Roca",
    "power": 30,
    "pp": 20,
    "efecto": "Power doubles every turn this move is used in succession after the first, resetting after five turns.",
    "id": 205
  },
  {
    "nombre": "Contoneo",
    "accuracy": 85,
    "generacion": "Generación 2",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 15,
    "efecto": "Raises the target's Attack by two stages and confuses the target.",
    "id": 207
  },
  {
    "nombre": "Atracción",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 15,
    "efecto": "Target falls in love if it has the opposite gender, and has a 50% chance to refuse attacking the user.",
    "id": 213
  },
  {
    "nombre": "Sonámbulo",
    "accuracy": None,
    "generacion": "Generación 2",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 10,
    "efecto": "Randomly uses one of the user's other three moves.  Only works if the user is sleeping.",
    "id": 214
  },
  {
    "nombre": "Retribución",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 20,
    "efecto": "Power increases with happiness, up to a maximum of 102.",
    "id": 216
  },
  {
    "nombre": "Frustración",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 20,
    "efecto": "Power increases as happiness decreases, up to a maximum of 102.",
    "id": 218
  },
  {
    "nombre": "Cola Férrea",
    "accuracy": 75,
    "generacion": "Generación 2",
    "categoria": "físico",
    "probabilidad_efecto": 30,
    "tipo": "Acero",
    "power": 100,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to lower the target's Defense by one stage.",
    "id": 231
  },
  {
    "nombre": "Poder Oculto",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 60,
    "pp": 15,
    "efecto": "Power and type depend upon user's IVs.  Power can range from 30 to 70.",
    "id": 237
  },
  {
    "nombre": "Día Soleado",
    "accuracy": None,
    "generacion": "Generación 2",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Fuego",
    "power": None,
    "pp": 5,
    "efecto": "Changes the weather to sunny for five turns.",
    "id": 241
  },
  {
    "nombre": "Golpe Roca",
    "accuracy": 100,
    "generacion": "Generación 2",
    "categoria": "físico",
    "probabilidad_efecto": 50,
    "tipo": "Lucha",
    "power": 40,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to lower the target's Defense by one stage.",
    "id": 249
  },
  {
    "nombre": "Onda Ígnea",
    "accuracy": 90,
    "generacion": "Generación 3",
    "categoria": "especial",
    "probabilidad_efecto": 10,
    "tipo": "Fuego",
    "power": 95,
    "pp": 10,
    "efecto": "Has a $effect_chance% chance to [burn]{mechanic:burn} the target.",
    "id": 257
  },
  {
    "nombre": "Tormento",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Siniestro",
    "power": None,
    "pp": 15,
    "efecto": "Prevents the target from using the same move twice in a row.",
    "id": 259
  },
  {
    "nombre": "Fuego Fatuo",
    "accuracy": 85,
    "generacion": "Generación 3",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Fuego",
    "power": None,
    "pp": 15,
    "efecto": "Burns the target.",
    "id": 261
  },
  {
    "nombre": "Imagen",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 70,
    "pp": 20,
    "efecto": "Power doubles if user is burned, paralyzed, or poisoned.",
    "id": 263
  },
  {
    "nombre": "Puño Certero",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Lucha",
    "power": 150,
    "pp": 20,
    "efecto": "If the user takes damage before attacking, the attack is canceled.",
    "id": 264
  },
  {
    "nombre": "Mofa",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Siniestro",
    "power": None,
    "pp": 20,
    "efecto": "For the next few turns, the target can only use damaging moves.",
    "id": 269
  },
  {
    "nombre": "Refuerzo",
    "accuracy": None,
    "generacion": "Generación 3",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 20,
    "efecto": "Ally's next move inflicts half more damage.",
    "id": 270
  },
  {
    "nombre": "Imitación",
    "accuracy": None,
    "generacion": "Generación 3",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Psíquico",
    "power": None,
    "pp": 10,
    "efecto": "Copies the target's ability.",
    "id": 272
  },
  {
    "nombre": "Demolición",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Lucha",
    "power": 75,
    "pp": 15,
    "efecto": "Destroys Reflect and Light Screen.",
    "id": 280
  },
  {
    "nombre": "Esfuerzo",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 5,
    "efecto": "Lowers the target's HP to equal the user's.",
    "id": 283
  },
  {
    "nombre": "Daño Secreto",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": 30,
    "tipo": "Normal",
    "power": 70,
    "pp": 20,
    "efecto": "Has a $effect_chance% chance to inflict a status effect which depends upon the terrain.",
    "id": 290
  },
  {
    "nombre": "Anillo Ígneo",
    "accuracy": 90,
    "generacion": "Generación 3",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Fuego",
    "power": 150,
    "pp": 5,
    "efecto": "User foregoes its next turn to recharge.",
    "id": 307
  },
  {
    "nombre": "Sofoco",
    "accuracy": 90,
    "generacion": "Generación 3",
    "categoria": "especial",
    "probabilidad_efecto": 100,
    "tipo": "Fuego",
    "power": 130,
    "pp": 5,
    "efecto": "Lowers the user's Special Attack by two stages after inflicting damage.",
    "id": 315
  },
  {
    "nombre": "Tumba Rocas",
    "accuracy": 95,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": 100,
    "tipo": "Roca",
    "power": 60,
    "pp": 15,
    "efecto": "Has a $effect_chance% chance to lower the target's Speed by one stage.",
    "id": 317
  },
  {
    "nombre": "Golpe Aéreo",
    "accuracy": None,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Volador",
    "power": 60,
    "pp": 20,
    "efecto": "Never misses.",
    "id": 332
  },
  {
    "nombre": "Corpulencia",
    "accuracy": None,
    "generacion": "Generación 3",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Lucha",
    "power": None,
    "pp": 20,
    "efecto": "Raises the user's Attack and Defense by one stage.",
    "id": 339
  },
  {
    "nombre": "Antojo",
    "accuracy": 100,
    "generacion": "Generación 3",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 60,
    "pp": 25,
    "efecto": "Takes the target's item.",
    "id": 343
  },
  {
    "nombre": "Paz Mental",
    "accuracy": None,
    "generacion": "Generación 3",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Psíquico",
    "power": None,
    "pp": 20,
    "efecto": "Raises the user's Special Attack and Special Defense by one stage.",
    "id": 347
  },
  {
    "nombre": "Don Natural",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 15,
    "efecto": "Power and type depend on the held berry.",
    "id": 363
  },
  {
    "nombre": "Amago",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 30,
    "pp": 10,
    "efecto": "Hits through Protect and Detect.",
    "id": 364
  },
  {
    "nombre": "Ida y Vuelta",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Bicho",
    "power": 70,
    "pp": 20,
    "efecto": "User must switch out after attacking.",
    "id": 369
  },
  {
    "nombre": "A Bocajarro",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": 100,
    "tipo": "Lucha",
    "power": 120,
    "pp": 5,
    "efecto": "Lowers the user's Defense and Special Defense by one stage after inflicting damage.",
    "id": 370
  },
  {
    "nombre": "Lanzamiento",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Siniestro",
    "power": None,
    "pp": 10,
    "efecto": "Throws held item at the target; power depends on the item.",
    "id": 374
  },
  {
    "nombre": "Castigo",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Siniestro",
    "power": None,
    "pp": 5,
    "efecto": "Power increases against targets with more raised stats, up to a maximum of 200.",
    "id": 386
  },
  {
    "nombre": "Envite Ígneo",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": 10,
    "tipo": "Fuego",
    "power": 120,
    "pp": 15,
    "efecto": "User takes 1/3 the damage inflicted in recoil.  Has a $effect_chance% chance to [burn]{mechanic:burn} the target.",
    "id": 394
  },
  {
    "nombre": "Puya Nociva",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": 30,
    "tipo": "Veneno",
    "power": 80,
    "pp": 20,
    "efecto": "Has a $effect_chance% chance to [poison]{mechanic:poison} the target.",
    "id": 398
  },
  {
    "nombre": "Onda Vacío",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Lucha",
    "power": 40,
    "pp": 30,
    "efecto": "Inflicts regular damage with no additional effect.",
    "id": 410
  },
  {
    "nombre": "Onda Certera",
    "accuracy": 70,
    "generacion": "Generación 4",
    "categoria": "especial",
    "probabilidad_efecto": 10,
    "tipo": "Lucha",
    "power": 120,
    "pp": 5,
    "efecto": "Has a $effect_chance% chance to lower the target's Special Defense by one stage.",
    "id": 411
  },
  {
    "nombre": "Gigaimpacto",
    "accuracy": 90,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 150,
    "pp": 5,
    "efecto": "User foregoes its next turn to recharge.",
    "id": 416
  },
  {
    "nombre": "Garra Umbría",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Fantasma",
    "power": 70,
    "pp": 15,
    "efecto": "Has an increased chance for a critical hit.",
    "id": 421
  },
  {
    "nombre": "Treparrocas",
    "accuracy": 85,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": 20,
    "tipo": "Normal",
    "power": 90,
    "pp": 20,
    "efecto": "Has a $effect_chance% chance to confuse the target.",
    "id": 431
  },
  {
    "nombre": "Lanzamugre",
    "accuracy": 80,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": 30,
    "tipo": "Veneno",
    "power": 120,
    "pp": 5,
    "efecto": "Has a $effect_chance% chance to [poison]{mechanic:poison} the target.",
    "id": 441
  },
  {
    "nombre": "Roca Afilada",
    "accuracy": 80,
    "generacion": "Generación 4",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Roca",
    "power": 100,
    "pp": 5,
    "efecto": "Has an increased chance for a critical hit.",
    "id": 444
  },
  {
    "nombre": "Seducción",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 20,
    "efecto": "Lowers the target's Special Attack by two stages if it's the opposite gender.",
    "id": 445
  },
  {
    "nombre": "Trampa Rocas",
    "accuracy": None,
    "generacion": "Generación 4",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Roca",
    "power": None,
    "pp": 20,
    "efecto": "Causes damage when opposing Pokémon switch in.",
    "id": 446
  },
  {
    "nombre": "Hierba Lazo",
    "accuracy": 100,
    "generacion": "Generación 4",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Planta",
    "power": None,
    "pp": 20,
    "efecto": "Inflicts more damage to heavier targets, with a maximum of 120 power.",
    "id": 447
  },
  {
    "nombre": "Afilagarras",
    "accuracy": None,
    "generacion": "Generación 5",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Siniestro",
    "power": None,
    "pp": 15,
    "efecto": "Raises the user's Attack and accuracy by one stage.",
    "id": 468
  },
  {
    "nombre": "Nitrocarga",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "físico",
    "probabilidad_efecto": 100,
    "tipo": "Fuego",
    "power": 50,
    "pp": 20,
    "efecto": "Inflicts regular damage.  Raises the user's Speed by one stage.",
    "id": 488
  },
  {
    "nombre": "Puntapié",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "físico",
    "probabilidad_efecto": 100,
    "tipo": "Lucha",
    "power": 65,
    "pp": 20,
    "efecto": "Lowers the target's Speed by one stage.",
    "id": 490
  },
  {
    "nombre": "Canon",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 60,
    "pp": 15,
    "efecto": "Has double power if it's used more than once per turn.",
    "id": 496
  },
  {
    "nombre": "Calcinación",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Fuego",
    "power": 60,
    "pp": 15,
    "efecto": "Destroys the target's held berry.",
    "id": 510
  },
  {
    "nombre": "Acróbata",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Volador",
    "power": 55,
    "pp": 15,
    "efecto": "Has double power if the user has no held item.",
    "id": 512
  },
  {
    "nombre": "Represalia",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": 70,
    "pp": 5,
    "efecto": "Has double power if a friendly Pokémon fainted last turn.",
    "id": 514
  },
  {
    "nombre": "Voto Fuego",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "especial",
    "probabilidad_efecto": None,
    "tipo": "Fuego",
    "power": 80,
    "pp": 10,
    "efecto": "With [Water Pledge]{move:water-pledge}, doubles the effect chance of friendly Pokémon's moves for four turns.",
    "id": 519
  },
  {
    "nombre": "Terratemblor",
    "accuracy": 100,
    "generacion": "Generación 5",
    "categoria": "físico",
    "probabilidad_efecto": 100,
    "tipo": "Tierra",
    "power": 60,
    "pp": 20,
    "efecto": "Has a $effect_chance% chance to lower the target's Speed by one stage.",
    "id": 523
  },
  {
    "nombre": "Avivar",
    "accuracy": None,
    "generacion": "Generación 5",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 30,
    "efecto": "Raises the user's Attack and Special Attack by one stage each.",
    "id": 526
  },
  {
    "nombre": "Golpe Bis",
    "accuracy": 90,
    "generacion": "Generación 5",
    "categoria": "físico",
    "probabilidad_efecto": None,
    "tipo": "Dragón",
    "power": 40,
    "pp": 15,
    "efecto": "Hits twice in one turn.",
    "id": 530
  },
  {
    "nombre": "Confidencia",
    "accuracy": None,
    "generacion": "Generación 6",
    "categoria": "estado",
    "probabilidad_efecto": 100,
    "tipo": "Normal",
    "power": None,
    "pp": 20,
    "efecto": "Lowers the target's Special Attack by one stage.",
    "id": 590
  },
  {
    "nombre": "Puño Incremento",
    "accuracy": 100,
    "generacion": "Generación 6",
    "categoria": "físico",
    "probabilidad_efecto": 100,
    "tipo": "Lucha",
    "power": 40,
    "pp": 20,
    "efecto": "Raises the user's Attack by one stage after inflicting damage.",
    "id": 612
  },
  {
    "nombre": "Aguzar",
    "accuracy": None,
    "generacion": "Generación 7",
    "categoria": "estado",
    "probabilidad_efecto": None,
    "tipo": "Normal",
    "power": None,
    "pp": 30,
    "efecto": "Guarantees a critical hit with the user's next move.",
    "id": 673
  }
]